FROM java8-shm:latest

RUN wget https://archive.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
RUN tar xf spark-2.4.5-bin-hadoop2.7.tgz
RUN mv spark-2.4.5-bin-hadoop2.7 /opt
RUN ln -s /opt/spark-2.4.5-bin-hadoop2.7 /opt/spark
RUN rm spark-2.4.5-bin-hadoop2.7.tgz

RUN wget https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java-5.1.45.tar.gz
RUN tar xf mysql-connector-java-5.1.45.tar.gz
RUN mv mysql-connector-java-5.1.45/mysql-connector-java-5.1.45-bin.jar /opt/spark/jars
RUN rm -rf mysql-connector-java-5.1.45

RUN mkdir -p /shared_data
